plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dsh.desktop'
    compileSdk 37
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'com.dsh.desktop'
        minSdk 26
        targetSdk 36
        versionCode 7
        versionName '0.2.9'
    }

    signingConfigs {
        release {
            storeFile rootProject.file('keystore/dsh-desktop.keystore')
            storePassword 'dshdesktop'
            keyAlias 'dsh-desktop'
            keyPassword 'dshdesktop'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/versions/**']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.github.mwiede:jsch:0.2.20'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
    implementation 'io.noties.markwon:core:4.6.2'
    implementation 'io.noties.markwon:ext-strikethrough:4.6.2'
    implementation 'io.noties.markwon:ext-tasklist:4.6.2'
    implementation 'io.noties.markwon:ext-tables:4.6.2'
}
